### ISSUE TITLE
can't compile: net-analyzer/monitoring-plugins-2.3.2::icinga

### ISSUE THREAD

**Issue by onkelbeh** [antonfischl1980/icinga#82]
sslutils.c:(.text+0x74): undefined reference to `SSL_CTX_use_certificate_chain_file'
collect2: error: ld returned 1 exit status

(dns fping gnutls ipv6 ldap mysql radius samba snmp ssh ssl -curl -game -postgres)

**Comment by onkelbeh** [comment]
dev-libs/openssl is 1.1.1q

**Comment by hydrapolic** [comment]
@onkelbeh this works for me on a stable machine: https://github.com/gentoo/gentoo/pull/28067

**Comment by antonfischl1980** [comment]
@hydrapolic well, onkelbeh seems to be onto something... I can reproduce it, but only USE="ssl gnutls" (both on at the same time)

**Comment by hydrapolic** [comment]
Ok, haven't tested with USE="gnutls ssl", that may be broken.

**Comment by onkelbeh** [comment]
confirm it compiles fine without gnutls.

**Comment by antonfischl1980** [comment]
I removed net-analyzer/monitoring-plugins from this repository, because all the patches I personally wanted have been applied upstream. No need to maintain this package here if it is the same on gentoo-repo.
